# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Moon's CodeSignal
tagline:             'Chronicle'
description:         'Personal blog of my Code Signal chronicle'
url:                 'https://denmark111.github.io'
baseurl:             '/CodeSignal'
paginate:            5
repo:                'https://github.com/denmark111/CodeSignal'

# About/contact
# author:
#   name:              Mark Otto
#   url:               https://twitter.com/mdo
#   email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
